# Generated by Django 4.2.29 on 2026-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('diretor', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(blank=True, max_length=200, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('nota_imdb', models.CharField(blank=True, max_length=10, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='filmes', to='filmes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('filmes', models.ManyToManyField(blank=True, related_name='listas', to='filmes.filme')),
            ],
        ),
    ]
